name: 'market_analytics'
version: '1.0.0'
config-version: 2

profile: 'market_analytics'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  market_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
